---
title: "Jerson Garcia CV"
author: Jerson Garcia
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis',
  echo=FALSE
)

library(glue)
library(tidyverse)

PDF_EXPORT <- FALSE
links <- c()

source('parsing_functions.R')

# load info
position_data <- read_csv('positions.csv')
```


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-github"></i> github.com/jjgarc34-hub
- <i class="fa fa-map-marker"></i> Texas


Skills {#skills}
--------------------------------------------------------------------------------

```{r}
skills <- tribble(
  ~skill,                ~level,
  "Field Service Engineering", 4.5,
  "EPI Tool Installation",       4.5,
  "R",                            3.5,
  "GitHub",               3.5,
  "R Markdown",           3.5,
  "Arduino / CAN",        3.5,
  "C#",                    3,
  "HTML / CSS",            3
)

build_skill_bars(skills)
```


About this CV {#disclaimer}
--------------------------------------------------------------------------------

Built from the DS4PS CV template using R Markdown and pagedown.

The position and project information is loaded from `positions.csv`.

Last updated on `r Sys.Date()`.



Main
================================================================================

Jerson Garcia {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "I am a Field Service Engineer at ASM where I manage EPI tool installations. My work is centered on coordinating installation work and supporting the technical side of tool installation. I am also completing graduate coursework at Arizona State University and have been building projects in R, GitHub, R Markdown, Arduino and CAN, and C#."

cat(sanitize_links(intro_text))
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```


Professional Experience {data-icon=tools}
--------------------------------------------------------------------------------

::: aside
My professional background is in field service engineering and EPI tool installation.
:::

```{r}
print_section(position_data, 'industry_positions')
```


Technical Projects {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'technical_projects')
```


Course Projects {data-icon=code}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'course_projects')
```


```{r}
if(PDF_EXPORT){
  cat("

Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")

  walk2(links, 1:length(links), function(link, index){
    print(glue('{index}. {link}'))
  })
}
```
